on:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  zip-files:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: dist/ manifest.json
          dest: result.zip
    
