on:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  zip-files:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: f1/
          dest: schemas.zip
      - uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: ${{ github.workspace }}/schemas.zip
          
  upload-schemas:
    needs: zip-files
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://7b76-180-248-33-205.ap.ngrok.io/upload'
        method: 'POST'
        contentType: 'multipart/form-data'
        file: ${{ github.workspace }}/schemas.zip
