on:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  zip-files:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: schema/
          dest: schemas.zip
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://b44f-36-85-74-42.ap.ngrok.io/upload'
          method: 'POST'
          contentType: 'multipart/form-data'
          files: '{ "schema": "${{ github.workspace }}/schemas.zip", "commit_id": "${{ github.event.pull_request.head.sha }}"}'
