on:
  pull_request:
    branches: 
      - main
    types: [closed]
    
jobs:
  zip-files:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: f1/
          dest: schemas.zip
  upload-schemas:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://localhost:8287/upload'
        method: 'POST'
        files: ${{ github.workspace }}/schemas.zip
